
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SHR = 22;
  public static final int DIVEQ = 29;
  public static final int POW = 16;
  public static final int STRING_LITERAL = 64;
  public static final int GTEQ = 19;
  public static final int SHL = 21;
  public static final int LTEQ = 18;
  public static final int CONCAT = 25;
  public static final int XOR = 7;
  public static final int REM = 6;
  public static final int SEMI = 51;
  public static final int OBRACK = 59;
  public static final int INT = 44;
  public static final int FOR = 40;
  public static final int MINUS = 3;
  public static final int EXPLICIT_RADIX_INTEGER_LITERAL = 62;
  public static final int REAL_LITERAL = 63;
  public static final int NOT = 13;
  public static final int AND = 23;
  public static final int LT = 10;
  public static final int NIL = 47;
  public static final int EQUALTO = 17;
  public static final int OR = 24;
  public static final int COMMA = 52;
  public static final int BWOR = 9;
  public static final int BEGIN = 57;
  public static final int ADT = 43;
  public static final int DIV = 5;
  public static final int PLUSEQ = 26;
  public static final int MINUSEQ = 27;
  public static final int PLUS = 2;
  public static final int IF = 38;
  public static final int DOT = 54;
  public static final int SYS = 49;
  public static final int XOREQ = 33;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int LPRAN = 55;
  public static final int error = 1;
  public static final int PPLUS = 14;
  public static final int MUL = 4;
  public static final int OREQ = 32;
  public static final int NEQ = 20;
  public static final int REMEQ = 30;
  public static final int BREAK = 42;
  public static final int EQ = 12;
  public static final int DECLARE = 34;
  public static final int MULEQ = 28;
  public static final int REAL = 45;
  public static final int SHLEQ = 35;
  public static final int COLON = 53;
  public static final int ELSE = 39;
  public static final int WHILE = 41;
  public static final int END = 58;
  public static final int STRING = 46;
  public static final int RPRAN = 56;
  public static final int GT = 11;
  public static final int BWAND = 8;
  public static final int CBRACK = 60;
  public static final int PRINT = 50;
  public static final int SHREQ = 36;
  public static final int ANDEQ = 31;
  public static final int IDENTIFIER = 65;
  public static final int INTEGER_LITERAL = 61;
  public static final int GO = 37;
  public static final int MMINUS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "REM",
  "XOR",
  "BWAND",
  "BWOR",
  "LT",
  "GT",
  "EQ",
  "NOT",
  "PPLUS",
  "MMINUS",
  "POW",
  "EQUALTO",
  "LTEQ",
  "GTEQ",
  "NEQ",
  "SHL",
  "SHR",
  "AND",
  "OR",
  "CONCAT",
  "PLUSEQ",
  "MINUSEQ",
  "MULEQ",
  "DIVEQ",
  "REMEQ",
  "ANDEQ",
  "OREQ",
  "XOREQ",
  "DECLARE",
  "SHLEQ",
  "SHREQ",
  "GO",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "BREAK",
  "ADT",
  "INT",
  "REAL",
  "STRING",
  "NIL",
  "RETURN",
  "SYS",
  "PRINT",
  "SEMI",
  "COMMA",
  "COLON",
  "DOT",
  "LPRAN",
  "RPRAN",
  "BEGIN",
  "END",
  "OBRACK",
  "CBRACK",
  "INTEGER_LITERAL",
  "EXPLICIT_RADIX_INTEGER_LITERAL",
  "REAL_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

